# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Experimentos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Dialogo(object):
    def setupUi(self, Dialogo):
        Dialogo.setObjectName("Dialogo")
        Dialogo.setEnabled(True)
        Dialogo.resize(570, 421)
        
        #boton procesar (el de abajo)
        self.btn_procesar = QtWidgets.QPushButton(Dialogo)
        self.btn_procesar.setEnabled(False)
        self.btn_procesar.setGeometry(QtCore.QRect(220, 370, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_procesar.setFont(font)
        self.btn_procesar.setObjectName("btn_procesar")

        #caja de texto (nombre del archivo de audio)
        self.caja_texto1 = QtWidgets.QTextBrowser(Dialogo)
        self.caja_texto1.setGeometry(QtCore.QRect(220, 70, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.caja_texto1.setFont(font)
        self.caja_texto1.setObjectName("caja_texto1")

        #Texto de arriba (1. Seleccione el audio)
        self.lbl_texto1 = QtWidgets.QLabel(Dialogo)
        self.lbl_texto1.setGeometry(QtCore.QRect(190, 0, 221, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_texto1.sizePolicy().hasHeightForWidth())
        self.lbl_texto1.setSizePolicy(sizePolicy)
        self.lbl_texto1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_texto1.setFont(font)
        self.lbl_texto1.setObjectName("lbl_texto1")

        #Texto de abajo (2. Seleccione el rostro)
        self.lbl_texto2 = QtWidgets.QLabel(Dialogo)
        self.lbl_texto2.setGeometry(QtCore.QRect(190, 120, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_texto2.setFont(font)
        self.lbl_texto2.setObjectName("lbl_texto2")

        #Botón radio 1
        self.radio_btn1 = QtWidgets.QRadioButton(Dialogo)
        self.radio_btn1.setGeometry(QtCore.QRect(60, 170, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_btn1.setFont(font)
        self.radio_btn1.setObjectName("radio_btn1")

        #Botón radio 2
        self.radio_btn2 = QtWidgets.QRadioButton(Dialogo)
        self.radio_btn2.setGeometry(QtCore.QRect(240, 170, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_btn2.setFont(font)
        self.radio_btn2.setObjectName("radio_btn2")

        #Botón radio 3
        self.radio_btn3 = QtWidgets.QRadioButton(Dialogo)
        self.radio_btn3.setGeometry(QtCore.QRect(430, 170, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_btn3.setFont(font)
        self.radio_btn3.setObjectName("radio_btn3")

        #Imagen 1
        self.gpc_imagen1 = QtWidgets.QGraphicsView(Dialogo)
        self.gpc_imagen1.setGeometry(QtCore.QRect(30, 200, 150, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpc_imagen1.sizePolicy().hasHeightForWidth())
        self.gpc_imagen1.setSizePolicy(sizePolicy)
        self.gpc_imagen1.setObjectName("gpc_imagen1")

        #Imagen 2
        self.gpc_imagen2 = QtWidgets.QGraphicsView(Dialogo)
        self.gpc_imagen2.setGeometry(QtCore.QRect(210, 200, 150, 150))
        self.gpc_imagen2.setObjectName("gpc_imagen2")

        #Imagen 3
        self.gpc_imagen3 = QtWidgets.QGraphicsView(Dialogo)
        self.gpc_imagen3.setGeometry(QtCore.QRect(390, 200, 150, 150))
        self.gpc_imagen3.setObjectName("gpc_imagen3")

        #Botón de arriba (Cargar)
        self.btn_cargar = QtWidgets.QPushButton(Dialogo)
        self.btn_cargar.setGeometry(QtCore.QRect(50, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_cargar.setFont(font)
        self.btn_cargar.setObjectName("btn_cargar")

        self.retranslateUi(Dialogo)
        QtCore.QMetaObject.connectSlotsByName(Dialogo)

    def retranslateUi(self, Dialogo):
        _translate = QtCore.QCoreApplication.translate
        Dialogo.setWindowTitle(_translate("Dialogo", "Audigest"))
        self.btn_procesar.setText(_translate("Dialogo", "Procesar"))
        self.caja_texto1.setHtml(_translate("Dialogo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Nombre del Archivo de Audio</span></p></body></html>"))
        self.lbl_texto1.setText(_translate("Dialogo", "1. Seleccione el audio"))
        self.lbl_texto2.setText(_translate("Dialogo", "2. Seleccione el rostro"))
        self.radio_btn1.setText(_translate("Dialogo", "Opción 1"))
        self.radio_btn2.setText(_translate("Dialogo", "Opción 2"))
        self.radio_btn3.setText(_translate("Dialogo", "Opción 3"))
        self.btn_cargar.setText(_translate("Dialogo", "Cargar "))
